---
- name: "Waiting for server to come back"
  local_action: wait_for
  args:
    host: "{{ (ansible_ssh_host|default(ansible_host)|default(inventory_hostname)) }}"
    port: 22
    timeout: 300
    delay: 15
    state: started
